version: "3"

services:

#  database-ha-testing:
#    build: .
#    ports:
#      - 5005:5005
#    volumes:
#      - "~/.sbt:/root/.sbt"
#      - "~/.ivy2:/root/.ivy2"
#      - ".:/opt/database-ha-testing"
#      - "/opt/database-ha-testing/target"
#      - "/opt/database-ha-testing/project/target"
#      - "/root/.sbt/1.0/plugins"

#  cassandra:
#    image: cassandra
#    ports:
#      - 9042:9042
#    volumes:
#      - "./cassandra:/opt/data/cassandra"

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users